name: Build & Type Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
      - 'web/**'
      - '.github/workflows/pr-checks.yaml'

jobs:
  checks:
    name: Type Check & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install API dependencies
        working-directory: api
        run: npm ci

      - name: Type check API
        working-directory: api
        run: npx tsc --noEmit

      - name: Install web dependencies
        working-directory: web
        run: npm i

      - name: Build website
        working-directory: web
        run: npm run build
        env:
          PUBLIC_API_URL: https://quicksync-api.ktz.me
